const PackageLink = [
    {
        id: '0',
        imgsrc: '/images/9.jpg',
        packageHeading: 'Testing',
        packagePrice: '₹5999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Rewari',
        travelCategory: 'Solo Traveling',
    },
    {
        id: '1',
        imgsrc: '/images/7.jpg',
        packageHeading: 'Testing1212',
        packagePrice: '₹6999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Gurgaon',
        travelCategory: 'HoneyMoon',
    },
    {
        id: '2',
        imgsrc: '/images/8.jpg',
        packageHeading: 'Testing1213',
        packagePrice: '₹7999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Pune',
        travelCategory: 'Group Traveling',
    },
    {
        id: '3',
        imgsrc: '/images/9.jpg',
        packageHeading: 'Testing1214',
        packagePrice: '₹8999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Pune',
        travelCategory: 'Family Trip',
    },
    {
        id: '4',
        imgsrc: '/images/6.jpg',
        packageHeading: 'Testing1214',
        packagePrice: '₹8999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Delhi',
        travelCategory: 'Family Trip',
    },
    {
        id: '5',
        imgsrc: '/images/7.jpg',
        packageHeading: 'Testing1214',
        packagePrice: '₹8999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Delhi',
        travelCategory: 'Family Trip',
    },
    {
        id: '6',
        imgsrc: '/images/8.jpg',
        packageHeading: 'Testing1214',
        packagePrice: '₹8999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Delhi',
        travelCategory: 'Family Trip',
    },
    {
        id: '7',
        imgsrc: '/images/9.jpg',
        packageHeading: 'Testing1214',
        packagePrice: '₹8999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Delhi',
        travelCategory: 'Family Trip',
    },
    {
        id: '8',
        imgsrc: '/images/6.jpg',
        packageHeading: 'Testing1214',
        packagePrice: '₹8999',
        packageDetails: 'Some quick example text to build on the card title.',
        fakePrice: '₹10999',
        from: 'Delhi',
        travelCategory: 'Family Trip',
    },



]


export default PackageLink;